server:
  port: 8890

spring:
  application:
    name: drom
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  mvc:
    favicon:
      enable: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: UUID
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
